# Generated by Django 4.2.7 on 2025-04-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0005_jobapplication_applicationhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReportProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.analyticsreport',),
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistoryProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.applicationstatushistory',),
        ),
        migrations.CreateModel(
            name='EmployerProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.employer',),
        ),
        migrations.CreateModel(
            name='JobAlertProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.jobalert',),
        ),
        migrations.CreateModel(
            name='JobApplicationProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.jobapplication',),
        ),
        migrations.CreateModel(
            name='JobMatchProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.jobmatch',),
        ),
        migrations.CreateModel(
            name='JobMetricsProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.jobmetrics',),
        ),
        migrations.CreateModel(
            name='JobPostingProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.jobposting',),
        ),
        migrations.CreateModel(
            name='JobSeekerProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.jobseeker',),
        ),
        migrations.CreateModel(
            name='JobViewLogProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.jobviewlog',),
        ),
        migrations.CreateModel(
            name='NotificationProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.notification',),
        ),
        migrations.CreateModel(
            name='PageViewProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.pageview',),
        ),
        migrations.CreateModel(
            name='SavedJobProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.savedjob',),
        ),
        migrations.CreateModel(
            name='SavedSearchProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.savedsearch',),
        ),
        migrations.CreateModel(
            name='UserActionProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.useraction',),
        ),
    ]
