# Generated by Django 5.1.7 on 2025-04-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='preferred_job_types',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_jobseekers', to='myapp.jobposting'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='preferred_locations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='professional_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='work_experience',
            field=models.TextField(blank=True),
        ),
    ]
