# Generated by Django 5.1.7 on 2025-04-08 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_jobseeker_education_jobseeker_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobviewlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='jobviewlog',
            name='referrer',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='jobviewlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='jobviewlog',
            index=models.Index(fields=['job'], name='myapp_jobvi_job_id_ef43d7_idx'),
        ),
        migrations.AddIndex(
            model_name='jobviewlog',
            index=models.Index(fields=['user'], name='myapp_jobvi_user_id_6f276f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobviewlog',
            index=models.Index(fields=['viewed_at'], name='myapp_jobvi_viewed__d48138_idx'),
        ),
    ]
