# Generated by Django 5.1.7 on 2025-04-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_jobviewlog_ip_address_jobviewlog_referrer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmetrics',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
