# Generated by Django 4.2.7 on 2025-04-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_jobapplication_applicationhistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='preferred_job_types',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='preferred_job_types',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
