# Generated by Django 4.2.7 on 2025-04-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_jobseeker_preferred_job_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='notify_application_status',
            field=models.BooleanField(default=True, help_text='Receive notifications about application status changes'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='notify_job_alerts',
            field=models.BooleanField(default=True, help_text='Receive notifications about new job matches'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='notify_messages',
            field=models.BooleanField(default=True, help_text='Receive notifications about new messages'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='notify_saved_searches',
            field=models.BooleanField(default=True, help_text='Receive notifications about saved search results'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.ManyToManyField(blank=True, to='myapp.skill'),
        ),
    ]
