# Generated by Django 4.2.7 on 2025-04-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_jobseeker_notify_application_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employer',
            name='myapp_emplo_user_id_4ad790_idx',
        ),
        migrations.RemoveIndex(
            model_name='employer',
            name='myapp_emplo_company_b48eda_idx',
        ),
        migrations.AddField(
            model_name='employer',
            name='notify_messages',
            field=models.BooleanField(default=True, help_text='Receive notifications about new messages'),
        ),
        migrations.AddField(
            model_name='employer',
            name='notify_new_applications',
            field=models.BooleanField(default=True, help_text='Receive notifications about new job applications'),
        ),
        migrations.AddIndex(
            model_name='employer',
            index=models.Index(fields=['can_post_jobs'], name='myapp_emplo_can_pos_c6491a_idx'),
        ),
    ]
