# Generated by Django 4.2.7 on 2025-04-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_employer_myapp_emplo_user_id_4ad790_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='country',
            field=models.CharField(choices=[('PH', 'Philippines')], default='PH', max_length=2),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='country',
            field=models.CharField(choices=[('PH', 'Philippines')], default='PH', max_length=2),
        ),
    ]
