# Generated by Django 4.2.7 on 2025-04-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_add_default_job_categories'),
        ('myapp', '0009_employer_country_jobseeker_country'),
    ]

    operations = [
    ]
