# Generated by Django 4.2.7 on 2025-04-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_add_default_skills_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='country',
            field=models.CharField(choices=[('PH', 'Philippines'), ('US', 'United States'), ('GB', 'United Kingdom'), ('CA', 'Canada')], default='PH', max_length=2),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='country',
            field=models.CharField(choices=[('PH', 'Philippines'), ('US', 'United States'), ('GB', 'United Kingdom'), ('CA', 'Canada')], default='PH', max_length=2),
        ),
    ]
