# Generated by Django 4.2.7 on 2025-05-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_employer_country_alter_jobseeker_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='credentials',
            field=models.TextField(blank=True, help_text='List your credentials, certifications, or awards.'),
        ),
        migrations.AddField(
            model_name='employer',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume (PDF, DOCX, etc.)', null=True, upload_to='employer_resumes/'),
        ),
    ]
